server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka 服务端的名称
  client:
    register-with-eureka: false #不向注册中心 注册自己
    fetch-registry: false #表示 自己就是服务注册中心 职责维护服务实例 并不需要检索服务
    service-url: #设置与eureka server交互的地址
      defaultZone: http://eureka7002.com:7002/eureka/
#  server:
#    # 该配置可以移除这种自我保护机制，防止失效的服务也被一直访问 (Spring Cloud默认该配置是 true)
#    enable-self-preservation: false
#    #该配置可以修改检查失效服务的时间，每隔30s检查失效服务，并移除列表 (Spring Cloud默认该配置是 60s）
#    eviction-interval-timer-in-ms: 10000
